name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Build Docker Image
        run: |
          docker build -t demo-py-app .
          echo ${{ secrets.AZURE_CLIENT_SECRET }} | docker login demomantis.azurecr.io --username ${{ secrets.AZURE_CLIENT_ID }} --password-stdin

      - name: Deploy to AKS
        run: | 
          az aks get-credentials --resource-group poc-ysq-mantis --name MyAksCluster
          kubectl set image deployment/demo-py-app demo-py-app=demomantis.azurecr.io/demo-py-app
          kubectl rollout status deployment/demo-py-app
