name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Build Docker Image
        run: |
          docker build -t demomantis.azurecr.io/demo-py-app:latest .

      - name: Push Docker Image to ACR
        run: |
          docker push demomantis.azurecr.io/demo-py-app:latest

      - name: Deploy to AKS
        run: | 
          az aks get-credentials --resource-group poc-ysq-mantis --name MyAksCluster
          kubectl set image deployment/demo-py-app demo-py-app=demomantis.azurecr.io/demo-py-app:latest
          kubectl rollout status deployment/demo-py-app
